global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["127.0.0.1:9091"]

  - job_name: "mlflow-serve"
    metrics_path: /metrics
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 15s
    relabel_configs:
      - source_labels: [__meta_docker_container_label_mlflow_serve]
        regex: true
        action: keep
      - source_labels: [__meta_docker_network_name]
        regex: mlops_default
        action: keep
      - source_labels: [__meta_docker_network_ip]
        regex: .+
        action: keep
      - source_labels: [__meta_docker_network_ip, __meta_docker_container_label_mlflow_port]
        separator: ':'
        regex: (.+):(.+)
        target_label: __address__
        replacement: $1:$2
      - source_labels: [__meta_docker_container_label_mlflow_model]
        target_label: model
      - source_labels: [__meta_docker_container_label_mlflow_alias]
        target_label: alias


  - job_name: "blackbox-http"
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets: [http://127.0.0.1:5000/health]
        labels:
          service: mlflow
      - targets: [http://127.0.0.1:__AIRFLOW_WEB_PORT__/health]
        labels:
          service: airflow
      - targets: [http://127.0.0.1:9022/minio/health/live]
        labels:
          service: minio
      - targets: [http://127.0.0.1:9091/-/healthy]
        labels:
          service: prometheus
      - targets: [http://127.0.0.1:3100/ready]
        labels:
          service: loki
      - targets: [http://127.0.0.1:3001/api/health]
        labels:
          service: grafana
      - targets: [https://127.0.0.1:8200/]
        labels:
          service: vault
      - targets: [http://127.0.0.1:5010/health]
        labels:
          service: autoserve
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 127.0.0.1:9115

  - job_name: "blackbox-mlflow-serve"
    metrics_path: /probe
    params:
      module: [http_2xx]
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 15s
    relabel_configs:
      - source_labels: [__meta_docker_container_label_mlflow_serve]
        regex: true
        action: keep
      - source_labels: [__meta_docker_network_name]
        regex: mlops_default
        action: keep
      - source_labels: [__meta_docker_network_ip]
        regex: .+
        action: keep
      - source_labels: [__meta_docker_network_ip, __meta_docker_container_label_mlflow_port]
        separator: ':'
        regex: (.+):(.+)
        target_label: __param_target
        replacement: http://$1:$2/ping
      - source_labels: [__param_target]
        target_label: instance
      - source_labels: [__meta_docker_container_label_mlflow_model]
        target_label: model
      - source_labels: [__meta_docker_container_label_mlflow_alias]
        target_label: alias
      - target_label: __address__
        replacement: 127.0.0.1:9115

  - job_name: "blackbox-tcp"
    metrics_path: /probe
    params:
      module: [tcp_connect]
    static_configs:
      - targets: [127.0.0.1:6432]
        labels:
          service: mlflow-db
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 127.0.0.1:9115
